CREATE TABLE Student (
  S_ID INT,
  FirstName VARCHAR(40) NOT NULL,
  LastName VARCHAR(40) NOT NULL,
  Email VARCHAR(40),
  Gender VARCHAR(1),
  Telephone VARCHAR(15),
  GPA FLOAT,
  D_ID INT,
  Advisor_ID INT,
  PRIMARY KEY (S_ID),
  FOREIGN KEY (D_ID) REFERENCES Department(D_ID)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT,
  FOREIGN KEY (Advisor_ID) REFERENCES Advisor(Advisor_ID)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT
);

CREATE TABLE Department (
  D_ID INT,
  Name VARCHAR(40),
  NoOfEmplyees INT,
  Telephone VARCHAR(15),
  Secretary VARCHAR(40),
  MGR_ID VARCHAR(40),
  PRIMARY KEY (D_ID),
  FOREIGN KEY (MGR_ID) REFERENCES Employee(E_ID)
  ON DELETE SET NULL
  ON UPDATE RESTRICT

);

CREATE TABLE Takes (
  S_ID INT,
  C_ID INT,
  Grade FLOAT NOT NULL,
  PRIMARY KEY (S_ID, C_ID)
  FOREIGN KEY (S_ID) REFERENCES Student(S_ID)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT,
  FOREIGN KEY (C_ID) REFERENCES Course(C_ID)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT
);




 CREATE TABLE Course (
  C_ID INT,
  Name VARCHAR(40) NOT NULL,
  CreditHours INT NOT NULL,
  DPRT_ID INT ,
  Lecturer_ID INT,
  PRIMARY KEY (C_ID),
  FOREIGN KEY (DPRT_ID) REFERENCES Department(D_ID)
  ON DELETE CASCADE
  ON UPDATE CASCADE,
  FOREIGN KEY (Lecturer_ID) REFERENCES Lecturer(Lecturer_ID)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT
);


CREATE TABLE Lecturer (
  Lecturer_ID INT,
  Ranking VARCHAR(40),
  PRIMARY KEY (Lecturer_ID),
  FOREIGN KEY (Lecturer_ID) REFERENCES Employee(E_ID)
  ON DELETE CASCADE
  ON UPDATE CASCADE
);

CREATE TABLE Prerequisite (
  AdvCourse_ID INT,
  PreCourse_ID INT,
  PRIMARY KEY (AdvCourse_ID, PreCourse_ID),
  FOREIGN KEY (AdvCourse_ID) REFERENCES Course(C_ID)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT,
  FOREIGN KEY (PreCourse_ID) REFERENCES Course(C_ID)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT
);

 CREATE TABLE Supervise (
  Lecturer_ID INT,
  P_ID INT,
  PRIMARY KEY (Lecturer_ID, P_ID),
  FOREIGN KEY (Lecturer_ID) REFERENCES Lecturer(Lecturer_ID)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT,
  FOREIGN KEY (P_ID) REFERENCES Project(P_ID)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT
);



CREATE TABLE Works On (
  P_ID INT,
  S_ID INT,
  PRIMARY KEY (P_ID, S_ID),
  FOREIGN KEY (P_ID) REFERENCES Project(P_ID)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT,
  FOREIGN KEY (S_ID) REFERENCES Student(S_ID)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT
);




CREATE TABLE Employee (
  E_ID  INT NOT NULL,
  FirstName VARCHAR(40) NOT NULL,
  LastName VARCHAR(40) NOT NULL,
  Email VARCHAR(40) NOT NULL,
  Gender VARCHAR(1) NOT NULL,
  Salary  INT ,
  Telephone VARCHAR(15) NOT NULL,
  PRIMARY KEY (E_ID)

);

CREATE TABLE Advisor (
  Advisor_ID  INT NOT NULL,
  Sessions VARCHAR(40) ,
  PRIMARY KEY (Advisor_ID),
  FOREIGN KEY (Advisor_ID) REFERENCES Employee (E_ID)
  ON DELETE CASCADE
  ON UPDATE CASCADE
);



CREATE TABLE Project (
  P_ID  INT NOT NULL,
  Name VARCHAR(40) NOT NULL,
  StartingDate DATE NOT NULL,
  EndingDate DATE NOT NULL,
  Budget  INT ,
  PRIMARY KEY (P_ID)
);

CREATE TABLE Office (
  O_ID  INT NOT NULL,
  Telephone VARCHAR(15) NOT NULL,
  Location VARCHAR(40)NOT NULL,
  DPRT_ID  INT NOT NULL,
  PRIMARY KEY (O_ID),
  FOREIGN KEY (DPRT_ID) REFERENCES Department (D_ID)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT
);

CREATE TABLE Dependent (
  Name VARCHAR(40) NOT NULL,
  E_ID  INT NOT NULL,
  Relationship VARCHAR(40),
  PRIMARY KEY (Name,E_ID),
  FOREIGN KEY (E_ID) REFERENCES Employee (E_ID)
  ON DELETE CASCADE
  ON UPDATE CASCADE
);

CREATE TABLE Training (
  T_ID  INT NOT NULL,
  Name VARCHAR(40)NOT NULL,
  NoOfWeeks  INT,
  DPRT_ID  INT NOT NULL,
  PRIMARY KEY (T_ID),
  FOREIGN KEY (DPRT_ID) REFERENCES Department (D_ID)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT
);
